In [13]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])

In [8]:
b = a.ravel().copy()
b

array([99,  2,  3,  4,  5,  6])

In [9]:
np.may_share_memory(a,b)

False

In [12]:
b[0] = 99
print(a)
print(b)

[[99  2  3]
 [ 4  5  6]]
[99  2  3  4  5  6]


In [14]:
a.shape

(2, 3)

In [15]:
b.shape

(6,)

In [18]:
b = b.reshape((2,3))

In [19]:
print(b)

[[99  2  3]
 [ 4  5  6]]


In [21]:
a.reshape((2,-1))

array([[99,  2,  3],
       [ 4,  5,  6]])

In [22]:
a

array([[99,  2,  3],
       [ 4,  5,  6]])

In [23]:
z = np.array([1,2,3])

In [24]:
z[:, np.newaxis] #เพิ่มในแนวตั้ง

array([[1],
       [2],
       [3]])

In [26]:
z[np.newaxis, :] #เพิ่มในแนวนอน

array([[1, 2, 3]])

In [31]:
a = np.arange(2*3*4).reshape(4,3,2)
a.shape

(4, 3, 2)

In [32]:
a = np.arange(4) #เพิ่มฟิวเข้าไปจนกว่าจะเต็ม
a.resize((2,3))

In [33]:
a

array([[0, 1, 2],
       [3, 0, 0]])

In [34]:
a = np.arange(4) #เพิ่มฟิวเข้าไปจนกว่าจะเต็มCont.
a.resize((2,3,4))
a

array([[[0, 1, 2, 3],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])